config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'

  Rails.application.routes.draw do
    resources :customers, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'input'
        get 'search'
        get 'edit_result'
      end
    end

    resources :pawns, only: [:index, :new, :create, :update, :edit] do
      collection do
        get 'result'
        get 'status_input'
        get 'status_search'
        get 'status_edit'
        get 'status_result'
        get 'edit_result'
      end
    end

    resources :purchases, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'result'
      end
    end

    resources :interests, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'search'
        get 'result'
      end
    end

    resources :searchs, only: [:index] do
      collection do
        get 'input_customer'
        get 'result_customer'
        get 'input_pawn'
        get 'result_pawn'
        get 'input_purchase'
        get 'result_purchase'
        get 'input_interest'
        get 'result_interest'
      end
    end
  end
end

app/models/pawn.rb
class Pawn < ApplicationRecord
  belongs_to :customer
  has_many :interests

  with_options presence: true do
    validates :item_name
    validates :item_price, numericality: { other_than: 0 }, format: { with: /\A^[0-9]+\z/ }
    validates :item_detail
    validates :item_status
  end

  def self.search(column, word)
    return Pawn.where("#{column} LIKE?","#{word}%").order("created_at DESC")
  end
  def self.search_pawn_status(column, word, status)
    return Pawn.find_by("#{column} LIKE? and item_status = ?","#{word}%", status)
  end

  def self.where_pawn_status(column, word, status)
    return Pawn.where("#{column} LIKE? and item_status = ?","#{word}%", status)
  end

  def self.check_pawn_status(column, word, status)
    return Pawn.where("#{column} LIKE? and item_status = ?","#{word}%", status).exists?
  end
end

app/controllers/pawns_controller.rb
class PawnsController < ApplicationController
  before_action :move_to_index, except: [:index, :status_input, :status_search, :edit, :update]
  before_action :move_to_index_id, only: [:edit, :update]
  before_action :set_pawn_format, only: [:result, :status_edit, :status_result, :edit_result]
  before_action :set_pawn_id, only: [:edit, :update]
  before_action :set_customer, only: [:new, :create]
  before_action :set_customer_pid, only: [:result, :status_edit, :status_result, :edit, :edit_result, :update]

  def index
  end

  def new
    @pawn = Pawn.new
  end

  def create
    @pawn = Pawn.new(pawn_params)
    if @pawn.save
      redirect_to result_pawns_path(@pawn.id)
    else
      render new_pawn_path
    end
  end

  def edit
  end

  def update
    if params[:process] == "edit"
      if @pawn.update(pawn_edit_params)
        redirect_to edit_result_pawns_path(@pawn.id)
      else
        render action: :edit
      end
    else
      if @pawn.update(pawn_status_params)
        if params[:process] == "return"
          redirect_to status_result_pawns_path(@pawn.id, process: "return")
        elsif params[:process] == "forfeit"
          redirect_to status_result_pawns_path(@pawn.id, process: "forfeit")
        end
      else
        render status_edit_pawns_path
      end
    end
  end

  def result

  end

  def status_input
  end

  def status_search
    @column = params[:column]
    word = params[:word]
    @pawns = SearchPawnsService.search_pawn_total_data(@column, word, 0)
  end

  def status_edit

  end

  def status_result
  end

  def edit_result

  end

private
  def set_pawn_format
    @pawn = Pawn.find(params[:format])
  end

  def set_pawn_id
    @pawn = Pawn.find(params[:id])
  end

  def set_customer
    @customer = Customer.find(params[:format])
  end

  def set_customer_pid
    @customer = Customer.find(@pawn.customer_id)
  end

  def move_to_index
    redirect_to root_path if params[:format] == nil
  end

  def move_to_index_id
    redirect_to root_path if params[:id] == nil
  end

  def pawn_params
    params.require(:pawn).permit(:item_name, :item_price, :item_detail, :item_remarks, :item_status)
                         .merge(customer_id: params[:format])
  end

  def pawn_status_params
    params.require(:pawn).permit(:item_status)
  end

  def pawn_edit_params
    params.require(:pawn).permit(:item_name, :item_price, :item_detail, :item_remarks, :item_status)
  end

end

app/helpers/pawns_helper.rb
module PawnsHelper
end

app/views/pawns/edit.html.erb
<body class='main'>
  <div class='title'>
    質情報編集
  </div>

  <%= render partial: "shared/pawn-form", locals: { url: pawn_path(@customer.id, process: "edit"), method: :patch } %>

  <%= render partial: "shared/toppage_button" %>
</body>

app/views/pawns/edit_result.html.erb
<body class='main'>
  <div class='title'>
    質情報を編集しました
  </div>
  <div class='search_result'>
    <div class='data_back'>
      <div class='customer_data_line'>
        <div class='result_category'>
          品物名
        </div>
        <div class='result_data'>
          <%= @pawn.item_name %>
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='result_category'>
          金額
        </div>
        <div class='result_data'>
          <%= @pawn.item_price.to_s(:delimited) %>円
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='result_category'>
          詳細
        </div>
        <div class='result_data'>
          <%= @pawn.item_detail %>
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='result_category'>
          備考
        </div>
        <div class='result_data'>
          <%= @pawn.item_remarks %>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: "shared/toppage_button" %>
</body>

app/views/pawns/index.html.erb
<body class='pawn_main'>
  <%= render partial: "shared/three-buttons-index" , locals: { page_title: "お客様情報を選択してください", new_data: new_customer_path("pawn"), search_data: input_customers_path("pawn") } %>
</body>

app/views/pawns/new.html.erb
<body class='pawn_main'>
  <div class='title'>
    質情報を入力してください
  </div>

  <%= render partial: "shared/pawn-form", locals: { url: pawns_path(@customer.id) } %>

  <%= render partial: "shared/toppage_button" %>
</body>

app/views/pawns/result.html.erb
<body class='pawn_main'>
  <div class='title'>
    質情報を登録しました
  </div>

  <%= render partial: "shared/display-pawn" , locals: { customer: @customer, pawn: @pawn } %>

  <%= render partial: "shared/toppage_button" %>
</body>

app/views/pawns/return_search.html.erb
<body class='return_top'>
  <div class='title'>質返還・検索結果</div>

  <% if @pawns == nil %>
    <div class="nil_message">
      該当するデータはありませんでした。検索をやり直してください。
    </div>
  <% else %>
    <%= render partial: "shared/search-result-interest", collection: @pawns, as: "pawn" %>
  <% end %>

  <%= render partial: "shared/back-button" , locals: { back_link: return_input_pawns_path } %>
</body>

app/views/pawns/status_edit.html.erb
<% if params[:process] == "return" %>
  <body class='return_top'>
    <div class='title'>質返還</div>
<div class='pawn_result_main'>
  <div class='customer_data_box'>
    <div class='box_title data_back'>
      お客様情報
    </div>
    <div>
      <div class='status_edit_data_line'>
        <div class='display_status_edit_category'>
          氏名
        </div>
        <div class='flex_left status_edit_data'>
          <div class='first_name_column'>
            <%= @customer.last_name %>
          </div>
          <div>
            <%= @customer.first_name %>
          </div>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='display_status_edit_category'>
          (カタカナ)
        </div>
        <div class='flex_left status_edit_data'>
          <div class='first_name_column'>
            <%= @customer.last_name_kana %>
          </div>
          <div>
            <%= @customer.first_name_kana %>
          </div>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='display_status_edit_category'>
          住所
        </div>
        <div class='status_edit_data'>
          <%= @customer.address %>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='display_status_edit_category'>
          備考
        </div>
        <div class='status_edit_data'>
          <%= @customer.remarks %>
        </div>
      </div>
    </div>
  </div>
  <div class='pawn_data_box'>
    <div class='box_title data_back'>
      品物情報
    </div>
    <div class='data_back'>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          品物名
        </div>
        <div class='interest_status_edit_data'>
          <%= @pawn.item_name %>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          金額
        </div>
        <div class='interest_status_edit_data'>
          <%= @pawn.item_price.to_s(:delimited) %>円
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          詳細
        </div>
        <div class='interest_status_edit_data'>
          <%= @pawn.item_detail %>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          備考
        </div>
        <div class='interest_status_edit_data'>
          <%= @pawn.item_remarks %>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          入質日
        </div>
        <div class='interest_status_edit_data'>
          <%= @pawn.created_at.strftime("%Y年%m月%d日") %>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          経過月数
        </div>
        <div class='interest_status_edit_data'>
          <%= interests_counter(@pawn.id) %>ヶ月
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          支払済利息
        </div>
        <div class='interest_status_edit_data'>
          <%= Interest.total_interest(@pawn.id) %>回
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          期限
        </div>
        <div class='interest_status_edit_data'>
          <%= pawn_timelimit(@pawn.id) %>
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          利息金額(1回)
        </div>
        <div class='interest_status_edit_data'>
          <%= interest_calculator(@pawn.item_price).to_s(:delimited) %>円
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          必要支払い回数
        </div>
        <div class='interest_status_edit_data'>
          <%= pay_number(@pawn.id, "return") %>回
        </div>
      </div>
      <div class='status_edit_data_line'>
        <div class='status_edit_item_category'>
          必要支払い金額
        </div>
        <div class='interest_status_edit_data'>
          <%= (interest_calculator(@pawn.item_price) * pay_number(@pawn.id, "return")).to_s(:delimited) %>円
        </div>
      </div>
    </div>
  </div>
</div>
    <div class="process_message">
      上記の質取引を返還済に変更します。
    </div>
    <div class='status_hidden_form'>
      <%= form_with model: @pawn, url: pawn_path(@pawn.id, process: "return"), method: :patch, local: true do |f| %>
        <%= f.hidden_field :item_status, value: 1 %>
        <%= f.submit "変更" ,class:"status_register_btn", data: { confirm: '返還処理してしていいですか?' } %>
      <% end %>
    </div>
<% elsif params[:process] == "forfeit" %>
  <body class='forfeit_top'>
    <div class='title'>質流れ</div>
    <%= render partial: "shared/display-pawn", locals: { pawn: @pawn, customer: @customer  } %>
    <div class="process_message">
      上記の質取引を質流れ処理します。
    </div>
    <div class='status_hidden_form'>
      <%= form_with model: @pawn, url: pawn_path(@pawn.id, process: "forfeit"), method: :patch, local: true do |f| %>
        <%= f.hidden_field :item_status, value: 2 %>
        <%= f.submit "変更" ,class:"status_register_btn", data: { confirm: '質流れ処理してしていいですか?' } %>
      <% end %>
    </div>
<% end %>
  <%= render partial: "shared/back-to-search-button" , locals: { search_link: status_input_pawns_path(params[:process]) } %>
</body>

app/views/pawns/status_input.html.erb
<% if params[:format] == "return" %>
  <body class="return_top">
    <div class="title">質返還・質情報検索</div>
    <%= render partial: "shared/search-pawn", locals: { process: status_search_pawns_path("return") } %>
<% elsif params[:format] == "forfeit" %>
  <body class="forfeit_top">
    <div class="title">質流れ・質情報検索</div>
    <%= render partial: "shared/search-pawn", locals: { process: status_search_pawns_path("forfeit") } %>
<% end %>
  <%= render partial: "shared/toppage_button" %>
</body>

app/views/pawns/status_result.html.erb
<% if params[:process] == "return" %>
  <body class='return_top'>
<% else params[:process] == "forfeit" %>
  <body class='forfeit_top'>
<% end %>
  <div class='title'>処理が完了しました</div>

  <%= render partial: "shared/display-status" , locals: { customer: @customer, pawn: @pawn } %>

  <%= render partial: "shared/toppage_button" %>

</body>

app/views/pawns/status_search.html.erb
<% if params[:format] == "return" %>
<body class='return_top'>
  <div class='title'>質返還・検索結果</div>
<% elsif params[:format] == "forfeit" %>
<body class='forfeit_top'>
  <div class='title'>質流れ・検索結果</div>
<% end %>

<% if @pawns == nil %>
  <div class="nil_message">
    該当するデータはありませんでした。検索をやり直してください。
  </div>
<% else %>
  <%= render partial: "shared/search-result-interest", collection: @pawns, as: "pawn" %>
<% end %>

  <%= render partial: "shared/back-button" , locals: { back_link: status_input_pawns_path(params[:format]) } %>
</body>