config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'

  Rails.application.routes.draw do
    resources :customers, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'input'
        get 'search'
        get 'edit_result'
      end
    end

    resources :pawns, only: [:index, :new, :create, :update, :edit] do
      collection do
        get 'result'
        get 'status_input'
        get 'status_search'
        get 'status_edit'
        get 'status_result'
        get 'edit_result'
      end
    end

    resources :purchases, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'result'
      end
    end

    resources :interests, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'search'
        get 'result'
      end
    end

    resources :searchs, only: [:index] do
      collection do
        get 'input_customer'
        get 'result_customer'
        get 'input_pawn'
        get 'result_pawn'
        get 'input_purchase'
        get 'result_purchase'
        get 'input_interest'
        get 'result_interest'
      end
    end
  end
end

app/views/shared/_back-button.html.erb
<div class='button_lines'>
  <div class='new_customer_btn'>
    <%= link_to back_link, data: { confirm: '前のページに戻っていいですか?' } do %>
      <div class='buttons'>
        前のページへ戻る
      </div>
    <% end %>
  </div>
  <div class='new_customer_btn'>
    <%= link_to root_path, data: { confirm: 'トップページに戻っていいですか?' } do %>
      <div class='buttons'>
        トップへ戻る
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_back-to-search-button.html.erb
<div class='button_lines'>
  <div class='new_customer_btn'>
    <%= link_to search_link, data: { confirm: '検索ページに戻っていいですか?' } do %>
      <div class='buttons'>
        検索ページへ戻る
      </div>
    <% end %>
  </div>
  <div class='new_customer_btn'>
    <%= link_to root_path, data: { confirm: 'トップページに戻っていいですか?' } do %>
      <div class='buttons'>
        トップへ戻る
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_customer-form.html.erb
<div class='form_layout'>
  <div class='second_frame'>
  <%= form_with model: @customer, url: url, local: true do |f| %>
    <div class='error_messages'>
      <%= render 'layouts/error_messages', model: f.object %>
    </div>
    <div class='form_layput_lines'>
      <div class='kanji_last_name'>
        <div class='form_label_text'>
          姓(漢字)
        </div>
        <div class='form_name_part'>
          <%= f.text_area :last_name, class:"last-name", id:"last-name", size:"10x1", maxlength:"10" %>
        </div>
      </div>
      <div class='kanji_first_name'>
        <div class='form_label_text'>
          名(漢字)
        </div>
        <div class='form_name_part'>
          <%= f.text_area :first_name, class:"first-name", id:"first-name", size:"10x1", maxlength:"10", autofocus: true %>
        </div>
      </div>
    </div>
    <div class='form_layput_lines'>
      <div class='kana_first_name'>
        <div class='form_label_text'>
          姓(カタカナ)
        </div>
        <div class='form_name_part'>
          <%= f.text_area :last_name_kana, class:"last-name", id:"last-name", size:"12x1", maxlength:"10" %>
        </div>
      </div>
      <div class='kana_last_name'>
        <div class='form_label_text'>
          名(カタカナ)
        </div>
        <div class='form_name_part'>
          <%= f.text_area :first_name_kana, class:"first-name", id:"first-name", size:"12x1", maxlength:"10" %>
        </div>
      </div>
    </div>
    <div class='address_part'>
      <div class='form_label_text'>
        住所
      </div>
      <div class='address_form'>
        <%= f.text_area :address, class:"address", id:"address", size:"30x2", maxlength:"1000" %>
      </div>
    </div>
    <div class='form_layput_lines'>
      <div class='phone_number_part'>
        <div class='form_label_text'>
          電話番号
        </div>
        <div class='phone_number_form'>
          <%= f.text_area :phone_number, class:"phone-number", id:"phone-number", size:"20x1", maxlength:"15" %>
        </div>
      </div>
      <div class='job_part'>
        <div class='form_label_text'>
          職業
        </div>
        <div class='job_form'>
          <%= f.text_area :job, class:"job", id:"job", size:"10x1", maxlength:"20" %>
        </div>
      </div>
    </div>
    <div class="form_layput_lines">
      <div class='birth_date_part'>
        <div class='form_label_text'>
          生年月日
        </div>
        <div class='birth_date_form'>
          <%= raw sprintf(
          f.date_select(
          :birth_date,
          class:'select-birth',
          id:"birth-date",
          use_month_numbers: true,
          prompt:'--',
          start_year: 1930,
          end_year: (Time.now.year - 17),
          date_separator: '%s'),
          "年", "月") + "日" %>
        </div>
      </div>
    </div>
    <div class="form_layput_lines">
      <div class='remarks_part'>
        <div class='form_label_text'>
          備考
        </div>
        <div class="remarks_form">
          <%= f.text_area :remarks, class:"remarks", id:"remarks", size:"30x3", maxlength:"200" %>
        </div>
      </div>
    </div>
    <div class='register-btn'>
      <%= f.submit "登録" ,class:"register-btn", data: { confirm: 'この情報で登録していいですか?' } %>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_display-interest.html.erb
<div class='interest_result_main'>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      お客様氏名
    </div>
    <div class='flex_left interest_result_data'>
      <div class='first_name_column'>
        <%= customer.last_name %>
      </div>
      <div>
        <%= customer.first_name %>
      </div>
    </div>
  </div>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      質番号
    </div>
    <div class='interest_result_data'>
      <%= pawn.id %>
    </div>
  </div>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      品物名
    </div>
    <div class='interest_result_data'>
      <%= pawn.item_name %>
    </div>
  </div>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      金額
    </div>
    <div class='interest_result_data'>
      <%= pawn.item_price.to_s(:delimited) %>円
    </div>
  </div>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      今回利息
    </div>
    <div class='interest_result_data'>
      <%= @interest.interests_number %>回
    </div>
  </div>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      累計利息
    </div>
    <div class='interest_result_data'>
      <%= Interest.total_interest(pawn.id) %>回
    </div>
  </div>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      入質日
    </div>
    <div class='interest_result_data'>
      <%= pawn.created_at.strftime("%Y年%m月%d日") %>
    </div>
  </div>
  <div class='customer_data_line'>
    <div class='interest_result_category'>
      期限
    </div>
    <div class='interest_result_data'>
      <%= pawn_timelimit(pawn.id) %>
    </div>
  </div>
</div>

app/views/shared/_display-pay-interests.html.erb
  <div class='interest_result_main'>
    <div class='customer_data_line'>
      <div class='interest_result_category'>
        入質日
      </div>
      <div class='interest_result_data'>
        <%= pawn.created_at.strftime("%Y年%m月%d日") %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_result_category'>
        経過月数
      </div>
      <div class='interest_result_data'>
        <%= interests_counter(pawn.id) %>ヶ月
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_result_category'>
        支払済利息
      </div>
      <div class='interest_result_data'>
        <%= Interest.total_interest(pawn.id) %>回
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_result_category'>
        期限
      </div>
      <div class='interest_result_data'>
        <%= pawn_timelimit(pawn.id) %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_result_category'>
        利息金額(1回)
      </div>
      <div class='interest_result_data'>
        <%= interest_calculator(pawn.item_price).to_s(:delimited) %>円
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_result_category'>
        必要支払い回数
      </div>
      <div class='interest_result_data'>
        <%= pay_number(pawn.id, "interest") %>回
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_result_category'>
        必要支払い金額
      </div>
      <div class='interest_result_data'>
        <%= (interest_calculator(pawn.item_price) * pay_number(pawn.id, "interest")).to_s(:delimited) %>円
      </div>
    </div>
  </div>

app/views/shared/_display-purchase.html.erb
<div class='pawn_result_main'>
  <div class='customer_data_box'>
    <div class='box_title data_back'>
      お客様情報
    </div>
    <div>
      <div class='customer_data_line'>
        <div class='interest_result_category'>
          お客様氏名
        </div>
        <div class='flex_left result_data'>
          <div class='first_name_column'>
            <%= customer.last_name %>
          </div>
          <div>
            <%= customer.first_name %>
          </div>
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='interest_result_category'>
          (カタカナ)
        </div>
        <div class='flex_left result_data'>
          <div class='first_name_column'>
            <%= customer.last_name_kana %>
          </div>
          <div>
            <%= customer.first_name_kana %>
          </div>
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='interest_result_category'>
          住所
        </div>
        <div class='result_data'>
          <%= customer.address %>
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='interest_result_category'>
          備考
        </div>
        <div class='result_data'>
          <%= customer.remarks %>
        </div>
      </div>
    </div>
  </div>
  <div class='pawn_data_box'>
    <div class='box_title data_back'>
      品物情報
    </div>
    <div class='data_back'>
      <div class='customer_data_line'>
        <div class='result_category'>
          品物名
        </div>
        <div class='result_data'>
          <%= purchase.buy_item_name %>
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='result_category'>
          金額
        </div>
        <div class='result_data'>
          <%= purchase.buy_item_price %>
        </div>
      </div>
      <div class='customer_data_line'>
        <div class='result_category'>
          詳細
        </div>
        <div class='result_data'>
          <%= purchase.buy_item_detail %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_display-status.html.erb
<div class='pawn_result_main'>
  <div class='data_back'>
    <div class='customer_data_line'>
      <div class='result_category'>
        お客様氏名
      </div>
      <div class='flex_left status_result_data'>
        <div class='first_name_column'>
          <%= customer.last_name %>
        </div>
        <div>
          <%= customer.first_name %>
        </div>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        品物名
      </div>
      <div class='status_result_data'>
        <%= pawn.item_name %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        金額
      </div>
      <div class='status_result_data'>
        <%= pawn.item_price.to_s(:delimited) %>円
      </div>
    </div>
  </div>
</div>

app/views/shared/_interest-form.html.erb
<div class="interest_form">
  <%= form_with model: @interest, url: process, local: true do |f| %>
    <div class='error_messages'>
      <%= render 'layouts/error_messages', model: f.object %>
    </div>
    <div class="form_field_flex">
      <div>
        <%= f.text_area :interests_number, class:"interests-number", id:"interests-number", size:"4x1", maxlength:"3" %>回
      </div>
      <div>
        <%= f.submit "登録" ,class:"register-btn", data: { confirm: 'この利息回数で登録していいですか?' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_purchase-form.html.erb
<div class='form_layout'>
  <div class='second_frame'>
    <%= form_with model: [@customer, @purchase], url: url,local: true do |f| %>
      <div class='error_messages'>
        <%= render 'layouts/error_messages', model: f.object %>
      </div>
      <div class='form_label_text'>
        品物名
      </div>
      <div class='form_name_part'>
        <%= f.text_area :buy_item_name, class:"item-name-box", id:"item-name", size:"20x1", maxlength:"40", autofocus: true %>
      </div>
      <div class='form_label_text'>
        金額
      </div>
      <div class='form_name_part'>
        <%= f.text_area :buy_item_price, class:"first-name", id:"first-name", size:"12x1", maxlength:"10" %>
      </div>
      <div class='form_label_text'>
        品物詳細
      </div>
      <div class='form_name_part'>
        <%= f.text_area :buy_item_detail, class:"item-detail", id:"item-detail", size:"30x5", maxlength:"300" %>
      </div>
      <div class='register-btn'>
        <%= f.submit "登録", class:"register-btn", data: { confirm: 'この情報で登録していいですか?' } %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_search-customer.html.erb
<div class='form_layout'>
  <div class='second_frame'>
    <div class="search-form">
      <%= form_with(scope: :search, url: url, method: :get, local: true) do |f| %>
        <div class="field">
          <%= select_tag 'column' ,options_for_select([['姓(漢字)', 'last_name'], ['姓(カタカナ)', 'last_name_kana'], ['質番号', 'id']]) %>
          <%= text_field_tag (:word) %>
        </div>
        <div class='register-btn'>
          <%= f.submit "検索" ,class:"register-btn", data: { confirm: 'この条件で検索していいですか?' } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_search-pawn.html.erb
<div class='interest_form'>
  <div class='search_comment'>
    検索項目を選択し、検索ワードを入力してください
  </div>
  <%= form_with(url: process, method: :get, local: true) do |f| %>
    <div class='search_pawn_field flex_around'>
      <%= select_tag 'column' ,options_for_select([['質番号', 'id'], ['姓(漢字)', 'last_name'], ['姓(カタカナ)', 'last_name_kana']]) %>
      <%= f.text_area :word, class:"pawn-search-word", id:"pawn-search-word", size:"10x1", maxlength:"16" %>
      <%= f.submit "検索" ,class:"short-text-register", data: { confirm: 'この条件で検索していいですか?' } %>
    </div>
  <% end %>
</div>

app/views/shared/_search-result-customer.html.erb
<div class='customer_search_result_main'>
  <div class='data_box'>
    <div class='customer_data_line'>
      <div class='result_category'>
        お客様氏名
      </div>
      <div class='flex_left result_data'>
        <div class='first_name_column'>
          <%= customer_record.last_name %>
        </div>
        <div>
          <%= customer_record.first_name %>
        </div>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        (カタカナ)
      </div>
      <div class='flex_left result_data'>
        <div class='first_name_column'>
          <%= customer_record.last_name_kana %>
        </div>
        <div>
          <%= customer_record.first_name_kana %>
        </div>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        住所
      </div>
      <div class='result_data'>
        <%= customer_record.address %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        生年月日
      </div>
      <div class='result_data'>
        <%= customer_record.birth_date.strftime("%Y年%m月%d日") %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        備考
      </div>
      <div class='result_data'>
        <%= customer_record.remarks %>
      </div>
    </div>
  </div>
  <div class='choise_box white_border'>
    <% if params[:format] == "pawn" %>
      <%= link_to new_pawn_path(customer_record.id), data: { confirm: 'このお客様でよろしいですか?' } do %>
        <div class='choise_btn'>
          選択
        </div>
      <% end %>
    <% elsif params[:format] == "purchase" %>
      <%= link_to new_purchase_path(customer_record.id), data: { confirm: 'このお客様でよろしいですか?' } do %>
        <div class='choise_btn'>
          選択
        </div>
      <% end %>
    <% elsif params[:format] == "edit" %>
      <%= link_to edit_customer_path(customer_record.id), data: { confirm: 'このお客様でよろしいですか?' } do %>
        <div class='choise_btn'>
          編集
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_search-result-interest.html.erb
<div class='pawn_result_main'>
  <div class='interest_search_data_box'>
    <div class='customer_data_line'>
      <div class='interest_category'>
        質番号
      </div>
      <div class='interest_search_result_data'>
        <%= pawn[:id] %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        お客様氏名
      </div>
      <div class='interest_search_result_data'>
        <%= pawn[:name] %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        品物名
      </div>
      <div class='interest_search_result_data'>
        <%= pawn[:item_name] %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        金額
      </div>
      <div class='interest_search_result_data'>
        <%= pawn[:price].to_s(:delimited) %>円
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        利息金額
      </div>
      <div class='interest_search_result_data'>
        <%= interest_calculator(pawn[:price]) %>円
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        備考
      </div>
      <div class='interest_search_result_data'>
        <%= pawn[:remarks] %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        入質日
      </div>
      <div class='interest_search_result_data'>
        <%= pawn[:date] %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        合計利息回数
      </div>
      <div class='interest_search_result_data'>
        <%= pawn[:total_interest] %>回
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='interest_category'>
        期限
      </div>
      <div class='interest_search_result_data'>
        <%= pawn_timelimit(pawn[:id]) %>
      </div>
    </div>
  </div>
  <div class='interest_search_choise_box white_border data_back'>
    <% if params[:format] == "interest" %>
      <%= link_to new_interest_path(pawn[:id]), data: { confirm: 'このお客様でよろしいですか?' } do %>
        <div class='choise_btn'>
          選択
        </div>
      <% end %>
    <% elsif params[:format] == "return" %>
      <%= link_to status_edit_pawns_path(pawn[:id], process: "return"), data: { confirm: 'このお客様でよろしいですか?' } do %>
        <div class='choise_btn'>
          選択
        </div>
      <% end %>
    <% elsif params[:format] == "forfeit"  %>
      <%= link_to status_edit_pawns_path(pawn[:id], process: "forfeit"), data: { confirm: 'このお客様でよろしいですか?' } do %>
        <div class='choise_btn'>
          選択
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_three-back-buttons.html.erb
<div class='button_lines'>
  <div class='new_customer_btn'>
    <%= link_to back_link, data: { confirm: '前のページに戻っていいですか?' } do %>
      <div class='buttons'>
        <%= page_name %>へ戻る
      </div>
    <% end %>
  </div>
  <div class='new_customer_btn'>
    <%= link_to searchs_path, data: { confirm: '検索トップに戻っていいですか?' } do %>
      <div class='buttons'>
        検索トップへ戻る
      </div>
    <% end %>
  </div>
  <div class='new_customer_btn'>
    <%= link_to root_path, data: { confirm: 'トップページに戻っていいですか?' } do %>
      <div class='buttons'>
        総合トップへ戻る
      </div>
    <% end %>
  </div>
</div>