config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'

  Rails.application.routes.draw do
    resources :customers, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'input'
        get 'search'
        get 'edit_result'
      end
    end

    resources :pawns, only: [:index, :new, :create, :update, :edit] do
      collection do
        get 'result'
        get 'status_input'
        get 'status_search'
        get 'status_edit'
        get 'status_result'
        get 'edit_result'
      end
    end

    resources :purchases, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'result'
      end
    end

    resources :interests, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'search'
        get 'result'
      end
    end

    resources :searchs, only: [:index] do
      collection do
        get 'input_customer'
        get 'result_customer'
        get 'input_pawn'
        get 'result_pawn'
        get 'input_purchase'
        get 'result_purchase'
        get 'input_interest'
        get 'result_interest'
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :pawns
  has_many :purchases

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana, format: { with: /\A^[ァ-ンヴー]+$\z/ }
    validates :first_name_kana, format: { with: /\A^[ァ-ンヴー]+$\z/ }
    validates :address
    validates :phone_number
    validates :birth_date
    validates :job
  end

  def self.search(column, word)
    if word != ""
      @customer = Customer.where("#{column} LIKE?","#{word}%")
    else
      @customer = nil
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :move_to_index, except: [:index, :new, :input, :search]
  before_action :move_to_index_id, only: [:edit, :update]
  before_action :set_customer_id, only: [:edit, :update]
  before_action :set_customer, only: [:show, :edit_result]

  def index
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      if params[:format] == "pawn"
        redirect_to new_pawn_path(@customer.id)
      elsif params[:format] == "purchase"
        redirect_to new_purchase_path(@customer.id)
      end
    else
      render new_customer_path
    end
  end

  def input
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to edit_result_customers_path(@customer.id)
    else
      render action: :edit
    end
  end

  def search
    @column = params[:column]
    word = params[:word]
    @customer = SearchCustomersService.search_customer_data(@column, word)
  end

  def edit_result
  end

private
  def move_to_index
    redirect_to root_path if params[:format] == nil
  end

  def move_to_index_id
    redirect_to root_path if params[:id] == nil
  end

  def set_customer
    @customer = Customer.find(params[:format])
  end

  def set_customer_id
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
                                     :address, :phone_number, :birth_date, :job)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      お客様情報編集
    </div>
  </div>
  <%= render partial: "shared/customer-form", locals: { customer: @customer, url: customer_path(@customer.id) } %>
  <%= render partial: "shared/three-back-buttons", locals: { back_link: input_customer_searchs_path, page_name: "お客様情報検索" } %>
</body>

app/views/customers/edit_result.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      お客様情報を編集しました
    </div>
  </div>
  <div class='search_result'>
    <div class='customer_data_line'>
      <div class='result_category'>
        お客様氏名
      </div>
      <div class='flex_left result_data'>
        <div class='first_name_column'>
          <%= @customer.last_name %>
        </div>
        <div>
          <%= @customer.first_name %>
        </div>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        (カタカナ)
      </div>
      <div class='flex_left result_data'>
        <div class='first_name_column'>
          <%= @customer.last_name_kana %>
        </div>
        <div>
          <%= @customer.first_name_kana %>
        </div>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        住所
      </div>
      <div class='result_data'>
        <%= @customer.address %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        生年月日
      </div>
      <div class='result_data'>
        <%= @customer.birth_date.strftime("%Y年%m月%d日") %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        電話番号
      </div>
      <div class='result_data'>
        <%= @customer.phone_number %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        職業
      </div>
      <div class='result_data'>
        <%= @customer.job %>
      </div>
    </div>
    <div class='customer_data_line'>
      <div class='result_category'>
        備考
      </div>
      <div class='result_data'>
        <%= @customer.remarks %>
      </div>
    </div>
  </div>
  <%= render partial: "shared/three-back-buttons", locals: { back_link: input_customer_searchs_path, page_name: "お客様情報検索" } %>
</body>

app/views/customers/index.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      PawnshopManager
    </div>
  </div>
  <div class='first_line button_lines'>
    <div class='first_line_button'>
      <%= link_to pawns_path do %>
        <div class='buttons top_page_btn'>
          入質
        </div>
      <% end %>
    </div>
    <div class='first_line_button'>
      <%= link_to interests_path do %>
        <div class='buttons top_page_btn'>
          利息
        </div>
      <% end %>
    </div>
    <div class='first_line_button'>
      <%= link_to purchases_path do %>
        <div class='buttons top_page_btn'>
          買取
        </div>
      <% end %>
    </div>
  </div>
  <div class='second_line button_lines'>
    <div class='second_line_button'>
      <%= link_to status_input_pawns_path("return") do %>
        <div class='buttons top_page_btn'>
          質返還
        </div>
      <% end %>
    </div>
    <div class='second_line_button'>
      <%= link_to status_input_pawns_path("forfeit") do %>
        <div class='buttons top_page_btn'>
          質流れ
        </div>
      <% end %>
    </div>
  </div>
  <div class='third_line button_lines'>
    <div class='third_line_button'>
      <%= link_to searchs_path do %>
        <div class='buttons top_page_btn'>
          データ検索
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/customers/input.html.erb
<% if params[:format] == "pawn" %>
  <body class='pawn_main'>
    <div class='title'>
      お客様情報検索
    </div>

    <%= render partial: "shared/search-customer", locals: { url: search_customers_path(pawn) } %>

    <%= render partial: "shared/back-button" , locals: { back_link: pawns_path } %>

  </body>
<% elsif params[:format] == "purchase" %>

  <body class='purchase_main'>
    <div class='title'>
      お客様情報検索
    </div>

    <%= render partial: "shared/search-customer", locals: { url: search_customers_path(purchase) } %>

    <%= render partial: "shared/back-button" , locals: { back_link: purchases_path } %>

  </body>
<% end %>

app/views/customers/new.html.erb
<% if params[:format] == "pawn" %>
  <body class='pawn_main'>
    <div class='title'>
      お客様情報を登録してください
    </div>

    <%= render partial: "shared/customer-form", locals: { customer: @customer, url: customers_path(pawn) } %>

    <%= render partial: "shared/back-button" , locals: { back_link: pawns_path } %>
  </body>

<% elsif params[:format] == "purchase" %>
    <body class='purchase_main'>
    <div class='title'>
      お客様情報を登録してください
    </div>

    <%= render partial: "shared/customer-form" , locals: { customer: @customer, url: customers_path(purchase) } %>

    <%= render partial: "shared/back-button", locals: { back_link: purchases_path } %>
  </body>
<% end %>

app/views/customers/search.html.erb
<% if params[:format] == "pawn" %>
  <body class='pawn_main'>
<% elsif params[:format] == "purchase" %>
  <body class='purchase_main'>
<% end %>

<div class='title'>検索結果</div>

<% if @customer == nil %>
  <div class="nil_message">
    該当するデータはありませんでした。検索をやり直してください。
  </div>
<% elsif params[:column] == "id" %>
  <%= render partial: "shared/search-result-customer", locals: {customer_record: @customer} %>
<% else %>
  <%= render partial: "shared/search-result-customer", collection: @customer, as: "customer_record" %>
<% end %>

  <%= render partial: "shared/back-button" , locals: { back_link: input_customers_path(params[:format]) } %>

</body>