config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'

  Rails.application.routes.draw do
    resources :customers, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'input'
        get 'search'
        get 'edit_result'
      end
    end

    resources :pawns, only: [:index, :new, :create, :update, :edit] do
      collection do
        get 'result'
        get 'status_input'
        get 'status_search'
        get 'status_edit'
        get 'status_result'
        get 'edit_result'
      end
    end

    resources :purchases, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'result'
      end
    end

    resources :interests, only: [:index, :new, :create, :edit, :update] do
      collection do
        get 'search'
        get 'result'
      end
    end

    resources :searchs, only: [:index] do
      collection do
        get 'input_customer'
        get 'result_customer'
        get 'input_pawn'
        get 'result_pawn'
        get 'input_purchase'
        get 'result_purchase'
        get 'input_interest'
        get 'result_interest'
      end
    end
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
  end

  def input_customer

  end

  def result_customer
    @column = params[:column]
    word = params[:word]
    @customer = SearchCustomersService.search_customer_data(@column, word)
  end

  def input_pawn

  end

  def result_pawn
    @column = params[:column]
    word = params[:word]
    @pawns = SearchPawnsService.search_pawn_total_data(@column, word, "free")
  end

  def input_purchase

  end

  def result_purchase
    @column = params[:column]
    word = params[:word]
    @purchases = SearchPurchasesService.search_purchase_total_data(@column, word)
  end

  def input_interest

  end

  def result_interest
    @column = params[:column]
    word = params[:word]
    @interests = SearchInterestsService.search_interest_total_data(@column, word)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/searchs/index.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      データ検索
    </div>
    <div class="middle_message">
      検索する項目を選択してください
    </div>
  </div>
  <div class='first_line button_lines'>
    <div class='first_line_button'>
      <%= link_to input_customer_searchs_path do %>
        <div class='buttons top_page_btn'>
          お客様
        </div>
      <% end %>
    </div>
    <div class='first_line_button'>
      <%= link_to input_pawn_searchs_path do %>
        <div class='buttons top_page_btn'>
          質取引
        </div>
      <% end %>
    </div>
  </div>
  <div class='second_line button_lines'>
    <div class='first_line_button'>
      <%= link_to input_interest_searchs_path do %>
        <div class='buttons top_page_btn'>
          利息
        </div>
      <% end %>
    </div>
    <div class='first_line_button'>
      <%= link_to input_purchase_searchs_path do %>
        <div class='buttons top_page_btn'>
          買取
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/searchs/input_customer.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      お客様データ検索
    </div>
    <div class="middle_message">
      検索する項目を選択してください
    </div>
  </div>
    <%= render partial: "shared/search-customer", locals: { url: result_customer_searchs_path("edit") } %>

    <%= render partial: "shared/back-button" , locals: { back_link: searchs_path } %>
</body>

app/views/searchs/input_interest.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      利息データ検索
    </div>
  </div>
  <div class='interest_form'>
    <div class='search_comment'>
      検索項目を選択し、検索ワードを入力してください
    </div>
    <%= form_with(url: result_interest_searchs_path, method: :get, local: true) do |f| %>
      <div class='search_pawn_field flex_around'>
        <%= select_tag 'column' ,options_for_select([['利息番号', 'id'], ['質番号', 'pawn_id'], ['姓(漢字)', 'last_name'], ['姓(カタカナ)', 'last_name_kana']]) %>
        <%= f.text_area :word, class:"pawn-search-word", id:"pawn-search-word", size:"10x1", maxlength:"16" %>
        <%= f.submit "検索" ,class:"short-text-register", data: { confirm: 'この条件で検索していいですか?' } %>
      </div>
    <% end %>
  </div>
    <%= render partial: "shared/back-button" , locals: { back_link: searchs_path } %>
</body>

app/views/searchs/input_pawn.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      質データ検索
    </div>
  </div>
    <%= render partial: "shared/search-pawn", locals: { process: result_pawn_searchs_path } %>

    <%= render partial: "shared/back-button" , locals: { back_link: searchs_path } %>
</body>

app/views/searchs/input_purchase.html.erb
<body class='main'>
  <div class='title-contents'>
    <div class='title'>
      買取データ検索
    </div>
  </div>
<div class='interest_form'>
  <div class='search_comment'>
    検索項目を選択し、検索ワードを入力してください
  </div>
  <%= form_with(url: result_purchase_searchs_path, method: :get, local: true) do |f| %>
    <div class='search_pawn_field flex_around'>
      <%= select_tag 'column' ,options_for_select([['買取番号', 'id'], ['姓(漢字)', 'last_name'], ['姓(カタカナ)', 'last_name_kana']]) %>
      <%= f.text_area :word, class:"pawn-search-word", id:"pawn-search-word", size:"10x1", maxlength:"16" %>
      <%= f.submit "検索" ,class:"short-text-register", data: { confirm: 'この条件で検索していいですか?' } %>
    </div>
  <% end %>
</div>
    <%= render partial: "shared/back-button" , locals: { back_link: searchs_path } %>
</body>

app/views/searchs/result_customer.html.erb
<body class='main'>
<div class="title">お客様情報検索結果</div>
  <% if @customer == nil %>
    <div class="nil_message">
      該当するデータはありませんでした。検索をやり直してください。
    </div>
  <% else %>
    <%= render partial: "shared/search-result-customer", collection: @customer, as: "customer_record" %>
  <% end %>
  <%= render partial: "shared/back-button" , locals: { back_link: input_customer_searchs_path } %>
</body>

app/views/searchs/result_interest.html.erb
<body class='main'>
<div class="title">利息情報検索結果</div>
  <% if @interests == nil %>
    <div class="nil_message">
      該当するデータはありませんでした。検索をやり直してください。
    </div>
  <% else %>
    <% @interests.each do |interest| %>
      <div class='interest_search_result_main form_field_flex'>
        <div class='interest_search_data_box'>
          <div class='customer_data_line'>
            <div class='interest_search_result_category'>
              お客様氏名
            </div>
            <div class='interest_search_result_data'>
              <%= interest[:name] %>
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='interest_search_result_category'>
              品物名
            </div>
            <div class='interest_search_result_data'>
              <%= interest[:item_name] %>
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='interest_search_result_category'>
              質取引金額            
            </div>
            <div class='interest_search_result_data'>
              <%= interest[:price].to_s(:delimited) %>円
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='interest_search_result_category'>
              利息金額(1回)
            </div>
            <div class='interest_search_result_data'>
              <%= interest_calculator(interest[:price]).to_s(:delimited) %>円
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='interest_search_result_category'>
              利息回数
            </div>
            <div class='interest_search_result_data'>
              <%= interest[:number] %>
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='interest_search_result_category'>
              合計利息金額
            </div>
            <div class='interest_search_result_data'>
              <%= (interest_calculator(interest[:price]) * interest[:number]).to_s(:delimited) %>円
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='interest_search_result_category'>
              利息取扱日
            </div>
            <div class='interest_search_result_data'>
              <%= interest[:date] %>
            </div>
          </div>
        </div>
        <div class='interest_search_choise_box white_border data_back'>
          <%= link_to edit_interest_path(interest[:id]), data: { confirm: 'このデータを編集してよろしいですか?' } do %>
            <div class='choise_btn'>
              編集
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= render partial: "shared/back-button" , locals: { back_link: input_interest_searchs_path } %>
</body>

app/views/searchs/result_pawn.html.erb
<body class='main'>
  <div class="title">質情報検索結果</div>
    <% if @pawns == nil %>
      <div class="nil_message">
        該当するデータはありませんでした。検索をやり直してください。
      </div>
    <% else %>
      <% @pawns.each do |pawn| %>
        <div class='pawn_result_main'>
          <div class='interest_search_data_box'>
            <div class='customer_data_line'>
              <div class='interest_category'>
                質番号
              </div>
              <div class='interest_search_result_data'>
                <%= pawn[:id] %>
              </div>
            </div>
            <div class='customer_data_line'>
              <div class='interest_category'>
                状態
              </div>
              <% if pawn[:status] == 0 %>
                <div class='interest_search_result_data'>
                  入質中
                </div>
              <% elsif pawn[:status] == 1 %>
                <div class='interest_search_result_data return_status'>
                  返還済
                </div>
              <% elsif pawn[:status] == 2 %>
                <div class='interest_search_result_data forfeit_status'>
                  質流れ
                </div>
              <% end %>
            </div>
            <div class='customer_data_line'>
              <div class='interest_category'>
                お客様氏名
              </div>
              <div class='interest_search_result_data'>
                <%= pawn[:name] %>
              </div>
            </div>
            <div class='customer_data_line'>
              <div class='interest_category'>
                品物名
              </div>
              <div class='interest_search_result_data'>
                <%= pawn[:item_name] %>
              </div>
            </div>
            <div class='customer_data_line'>
              <div class='interest_category'>
                金額
              </div>
              <div class='interest_search_result_data'>
                <%= pawn[:price].to_s(:delimited) %>円
              </div>
            </div>
            <div class='customer_data_line'>
              <div class='interest_category'>
                備考
              </div>
              <div class='interest_search_result_data'>
                <%= pawn[:remarks] %>
              </div>
            </div>
            <div class='customer_data_line'>
              <div class='interest_category'>
                入質日
              </div>
              <div class='interest_search_result_data'>
                <%= pawn[:date] %>
              </div>
            </div>
            <div class='interest_search_choise_box white_border data_back'>
              <%= link_to edit_pawn_path(pawn[:id]), data: { confirm: 'このデータを編集してよろしいですか?' } do %>
                <div class='choise_btn'>
                  編集
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    
  <%= render partial: "shared/back-button" , locals: { back_link: input_pawn_searchs_path } %>
</body>

app/views/searchs/result_purchase.html.erb
<body class='main'>
  <div class="title">質情報検索結果</div>
  <% if @purchases == nil %>
    <div class="nil_message">
      該当するデータはありませんでした。検索をやり直してください。
    </div>
  <% else %>
    <% @purchases.each do |purchase| %>
      <div class='customer_search_result_main'>
        <div class='data_box'>
          <div class='customer_data_line'>
            <div class='result_category'>
              お客様氏名
            </div>
            <div class='result_data'>
              <%= purchase[:name] %>
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='result_category'>
              品物名
            </div>
            <div class='result_data'>
              <%= purchase[:item_name] %>
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='result_category'>
              金額
            </div>
            <div class='result_data'>
              <%= purchase[:price] %>
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='result_category'>
              詳細
            </div>
            <div class='result_data'>
              <%= purchase[:detail] %>
            </div>
          </div>
          <div class='customer_data_line'>
            <div class='result_category'>
              買取日
            </div>
            <div class='result_data'>
              <%= purchase[:date] %>
            </div>
          </div>
        </div>
        <div class='choise_box white_border'>
          <%= link_to edit_purchase_path(purchase[:id]), data: { confirm: 'この買取データを編集しますか?' } do %>
            <div class='choise_btn'>
              編集
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= render partial: "shared/back-button" , locals: { back_link: input_purchase_searchs_path } %>
</body>